orkestral/venom

src/api/whatsapp.ts

downloadFile get file if message isMMS

downloadFile adjustment

---

README.md
src/api/helpers/dowload-image-file.ts
src/api/helpers/index.ts
src/api/helpers/select-sticker.ts
src/api/layers/group.layer.ts
src/api/layers/sender.layer.ts
src/lib/wapi/functions/add-participant.js
src/lib/wapi/wapi.js

Função nova: sendImageAsStickerGif()

Nova função e correções 

---

src/controllers/initializer.ts

fix bug autoclose

---

src/lib/wapi/functions/check-send-exist.js
src/lib/wapi/functions/fix-chat.js
src/lib/wapi/functions/get-chat.js
src/lib/wapi/functions/send-contact-vcard-list.js
src/lib/wapi/functions/send-contact-vcard.js
src/lib/wapi/functions/send-file.js
src/lib/wapi/functions/send-link-preview.js
src/lib/wapi/functions/send-location.js
src/lib/wapi/functions/send-message.js
src/lib/wapi/wapi.js

Fixed send by group id
For test purpose: https://wa.me/5543999011050

fix: Fixed send by group id (close #151)

---

src/api/helpers/download-image-file.ts
src/api/helpers/index.ts

`dowload-image-file.ts → download-image-file.ts`
`dowloadFileImgHttp → downloadFileImgHttp`
For test purpose: https://wa.me/5543999011050

chore: Fixed typo

---

README.md
src/config/create-config.ts
src/controllers/browser.ts

Fix(#222): add option to inject options into puppeteer

---

README.md

put all the statuses inside a table and correct the spelling of "client"

README: improve readability and fix a small typo

---

README.md
src/api/layers/sender.layer.ts

It works the same as gif files, and has the same color loss problem as gifs: https://github.com/orkestral/venom/issues/277#issuecomment-719068476

Add StickerGif compatibility with Webp format

---

.gitignore
docs/about.md

Some classes and functions need to be documented, but there's the most used.

Provides a documentation for venom

---

src/api/helpers/filename-from-mimetype.ts
src/api/layers/sender.layer.ts

Added function `sendImageFromBase64` to send images from base64

feat: Send image from base64

---

.github/workflows/nightly.yml
.github/workflows/publish.yml
.gitignore
.npmignore
package-lock.json
package.json
typedoc.json

Example: https://edgardmessias.github.io/venom/

docs: Added automated documentation

---

src/api/layers/retriever.layer.ts
src/api/model/chat.ts
src/api/model/contact.ts
src/api/model/message.ts
src/lib/wapi/serializers/serialize-message.js
src/lib/wapi/wapi.js
src/types/WAPI.d.ts

deprecated isOnline and lastSeen attributes

feat: Added method getLastSeen (close #303)

---

src/api/helpers/download-file.ts
src/api/helpers/index.ts
src/api/layers/profile.layer.ts
src/api/layers/sender.layer.ts

Now it will work with url like:
http://res.cloudinary.com/drfanzhnn/video/upload/fl_lossy,q_50/v1605162254/EmmkwpVXEAAYSet_bxytzc.gif

fix: Fixed url validation for send from URL

---

src/controllers/initializer.ts
src/index.ts

To test (it takes a while): `npm install github:edgardmessias/venom#feat_create`

feat: Added option to create from object

---

src/lib/wapi/functions/add-participant.js
src/lib/wapi/functions/demote-participant.js
src/lib/wapi/functions/promote-participant.js
src/lib/wapi/functions/remove-participant.js

Fixed group functions:
* `client.addParticipant`
* `client.removeParticipant`
* `client.promoteParticipant`
* `client.demoteParticipant`
To test (it takes a while): `npm install github:edgardmessias/venom#fix_group_functions`

fix: Fixed group functions (close #416)

---

src/api/layers/host.layer.ts
src/api/layers/listener.layer.ts
src/controllers/auth.ts
src/controllers/browser.ts
src/controllers/initializer.ts
src/lib/wapi/functions/send-seen.js
src/lib/wapi/listeners/add-on-state-change.js
src/lib/wapi/wapi.js

To test (it takes a while): `npm install github:edgardmessias/venom#fix_script_injection`

fix: Improved script injection

---

src/lib/wapi/functions/send-seen.js

To test (it takes a while): `npm install github:edgardmessias/venom#fix_sendseen`

fix: Fixed sendSeen call

---

src/controllers/browser.ts
src/controllers/initializer.ts

Fixes #421.
- Fixed error output for browser connection or browser launch
To test (it takes a while): `npm install github:edgardmessias/venom#fix_browser`

fix: Fixed browser error output

---

src/api/layers/profile.layer.ts
src/lib/wapi/functions/set-profile-pic.js
src/types/WAPI.d.ts

Fixes #359, #426.
- Fixed set profile picture for yourself
- Allow set group picture
To test (it takes a while): `npm install github:edgardmessias/venom#fix_profilepic`

fix: Fixed set profile picture (fix #359, close #426)

---

src/api/layers/host.layer.ts

- Reset autoclose interval after QRCode read
To test (it takes a while): `npm install github:edgardmessias/venom#fix_autoclose`

fix: Reset autoclose interval after QRCode read

---

src/api/model/contact-status.ts

Fixes #461  .
append optional 'stale' property to ContactStatus

feat: optional 'stale' property to ContactStatus (close #461)

---

src/lib/wapi/serializers/serialize-contact.js

Fixes #523 .
- Fixed contact thumbmail
To test (it takes a while): `npm install github:edgardmessias/venom#fix_contact_thumbnail`
Pix (Brazil): 28571c52-8b9b-416c-a18f-8e5246060881

fix: Fixed contact thumbmail (close #523)

---

src/api/whatsapp.ts

Fix issues[ #585](https://github.com/orkestral/venom/issues/585)
npm install github:matheust3/venom#issues-585
Tested!

fix: issues #585

---

src/lib/wapi/store/store-objects.js

Fixes #631 
store-objects:
- lint MediaCollection
- check toString is function before call in MsgKey module

fix: MsgKey check toString is function

---

README.md

Added Some Emoji

---

src/api/layers/sender.layer.ts

make  sendImageAsSticker accept row base64

make sendImageAsSticker also accepts base64 

---

src/lib/wapi/wapi.js

Patch for WhatsApp Web v2.2126.10

---

package-lock.json
package.json

Revert "chore(deps): bump ora from 5.4.1 to 6.0.1"

---

src/lib/wapi/listeners/add-on-state-change.js

Fixes addOnStateChange and addOnStreamChange.
Correção no listeners de estados, antes era adquirido pelo default e atualmente pelo Socket.

Fix addOnStateChange and addOnStreamChange

---

src/api/layers/listener.layer.ts

the function window.WAPI.onMessage do not exist in the project, so I changed to use the right functions

fix onMessage and onAck listeners

---

src/controllers/initializer.ts

Improved display of debug messages and fix in invalid Chrome debug URL

---

src/lib/wapi/business/send-message-with-buttons.js
src/lib/wapi/functions/get-unread-messages.js
src/lib/wapi/functions/load-earlier-messages-til-date.js
src/lib/wapi/functions/open-chat.js
src/lib/wapi/functions/send-file.js
src/lib/wapi/functions/send-image-with-product.js
src/lib/wapi/functions/send-ptt.js
src/lib/wapi/functions/send-video-as-gif.js

after the new whatsapp update, the access to the models property of the msg and chat classes is causing an undefined error, I changed it to use the _models property, I don't know if the error also happens in the mediaCollection class, but to avoid errors, I put it in it too

fix models undefined issue

---

src/lib/wapi/functions/delete-messages-all.js
src/lib/wapi/store/store-objects.js

Fixes # .
fix delete messages, the method sendRevokeMsgs moved to a new module, that not recognize in ``getStore`` method.

fix-delete-messages-all

---

src/lib/wapi/functions/check-number-status.js

Fixes #1790 
alterado função queryExists para queryPhoneExists no check-number-status

fix: queryExists

---

src/lib/wapi/functions/check-number-status.js
src/lib/wapi/functions/check-send-exist.js

This commit fix the e.isLid is not a function issue https://github.com/orkestral/venom/issues/1792 https://github.com/orkestral/venom/issues/1790

fix: e.isLid is not a function

---

src/lib/wapi/functions/get-all-unread-messages.js

Ack estava incorreto no filtro, deve ser 1 e não -1

fix: getAllUnreadMessages ack incorreto

---

src/controllers/initializer.ts

Alterando a ordem de inicialização

---

src/controllers/browser.ts

chore: Re-added poweredBy config

---

package.json
src/api/layers/retriever.layer.ts

Fix checkNumberStatus()
Update wa-js

Fix checkNumberStatus

---

src/lib/wapi/functions/process-files.js
src/lib/wapi/help/process-files.js

Reference 
https://github.com/orkestral/venom/issues/2482

Fixed sendFile error

---

Docs.md
README.md
docs/getting-started/basic-functions.md
src/lib/wapi/functions/simulate-typing.js

- stopTyping is no longer supported by venom.  Remove documentation references to it.

Remove references to and remaining code for stopTyping

---

src/lib/wapi/functions/get-group-participant-ids.js
src/lib/wapi/functions/promote-participant.js

Fixes # 
Promote Participant functionality Fixed.

bugFix: promoteParticipant

---

src/controllers/browser.ts
src/lib/wapi/api.js
src/lib/wapi/functions/create-newsletter.js
src/lib/wapi/functions/index.js
src/lib/wapi/functions/process-files.js
src/lib/wapi/functions/send-file.js
src/lib/wapi/help/process-files.js
src/lib/wapi/store/store-objects.js
src/lib/wapi/wapi.js
yarn.lock

- [Create Newsletter](#create-newsletter)
- [Get Newsletter Subscribers] (Coming Soon)
**window.WAPI.createNewsLetter(name,description,picture)**
Response:
```json
{
"idJid": "120363183704050500@newsletter",
"newsletterCreationTimeMetadataMixin": {
"creationTimeValue": 1701171938
},
"newsletterHandleMetadataMixin": null,
"newsletterInviteLinkMetadataMixin": {
"inviteCode": "0029VaFAtPhG3R3oYjOgYm14"
},
"newsletterNameMetadataMixin": {
"nameId": "1701171938350411",
"nameUpdateTime": 1701171938350411,
"nameElementValue": "NOV28Newsletter"
},
"newsletterSubscribersMetadataMixin": {
"subscribersCount": 0
},
"newsletterMutedMetadataMixin": {
"mutedState": "on"
},
"newsletterVerificationMetadataMixin": {
"verificationState": "unverified"
},
"newsletterStateMetadataMixin": {
"stateType": …
```

added Newsletter Support : createNewsletter

---

Docs.md
README.md
src/lib/wapi/functions/send-buttons.js

Fixes # .
- Refactored sendButton parameters

refactor: update sendButtons function parameters with SenderLayer method

---

src/api/layers/sender.layer.ts
src/types/WAPI.d.ts

Fixes # .
-Fixed send buttons function
it seems that the arguments which are being sent were mixed up for some reason
To test (it takes a while): `npm install github:ziadmontaser/venom#<branch>`

Fixed send buttons

---

.github/workflows/build.yml
.github/workflows/nightly.yml
CHANGELOG.md
package-lock.json
package.json

Added support for newsletter
Fixed send link preview

Release 5.0.23

---

README.md
package-lock.json
package.json
src/api/layers/sender.layer.ts
src/api/whatsapp.ts
src/types/WAPI.d.ts
yarn.lock

Improve the resiliency and reliability.

Use evaluate instead of injecting script tags

---

package-lock.json
package.json
src/controllers/browser.ts
yarn.lock

remove the is-root dependency.  It is a single line we can put directly in this project.

remove the is-root dependency

---

package-lock.json
package.json
src/api/helpers/decrypt.ts
tsconfig.json
yarn.lock

It is a single line we can put directly in this project.

remove the atob dependency.  
