README.md
src/config/create-config.ts
src/controllers/initializer.ts

option to pass, on session create, to disable spinnies
animation.
spinnies are fun, spinnies on docker and kubernetes aren't,
since it may log many lines or bug the visualizer.
this option is
default false (which keeps spinnies animations normally), if passed
disableSpins = true, it will disable the spinnies animation.

feat(initializer, create-config): disable spinnies option

---

package.json
src/api/layers/sender.layer.ts

**PT**
Adicionado um RegEx para verificar se a URI da imagem é local ou remota. Caso seja remota, obtêm a base64 da imagem e faz o envio.
**EN**
Added an RegEx to verify if the image's URL is local or remote. If it's remote, get the base64 string then send it.

feat: Envio de imagens diretamente da internet

---

src/controllers/initializer.ts

As mentioned in issue #180, when using TypeScript and calling the "create" function, it was expecting <false | Whatsapp>.
I changed the "create" function, replaced the "return false" to a simple spinner fail.
Besides, I've set manually the expected return from the "create" function

fixed return type of create function

---

src/lib/wapi/functions/send-contact-vcard-list.js
src/lib/wapi/functions/send-contact-vcard.js
src/lib/wapi/functions/send-location.js

To test (it takes a while): `npm install github:edgardmessias/venom#fix_undefined_erro`

fix: Fixed undefined from sendLocation and sendContactVcard (close #410)

---

src/lib/wapi/functions/download-media.js

Fixes #456.
- Fixed downloadMedia for videos on Chromium
To test (it takes a while): `npm install github:edgardmessias/venom#fix_download_media_chromium`

fix: Fixed downloadMedia for videos on Chromium (close #456)

---

src/api/model/message.ts
src/api/whatsapp.ts

Fixes #572.
- when the value is null in the clienteUrl field it is possible to recover the value in the field deprecatedMms3Url
To test (it takes a while): npm install github:elciorodrigo/venom#issue572

fix: client url undefined

---

src/api/layers/host.layer.ts

After calling the autoclose within the condition autheticated false the function isAuthenticated returns object with error http but enters the condition of QRCode Success because the condition is not checking if it is only equals true
After changing condition the status is seted correctelly on error or on success in reading QR Code

Fix authenticated status check when error

---

src/api/layers/sender.layer.ts

expand error message and documentation explaining that when sending base64 files it must begin with "data:(yourMimeType);base64," since helper base64MimeType tests for that entire string

better error message for posiblly missing mimeType

---

src/lib/wapi/functions/check-send-exist.js

Fixes # .
Fixed the chatid to Wid of the chat room when check some store infos on sendExist.
This will fix, for example, send message on new version of Whatsapp.
To test (it takes a while): `npm install github:lucawen/venom#hotfix/update_wpp_version

Update whatsapp version to 2.2208.7. 'Wid' for chat check on sendExist

---

src/lib/wapi/functions/get-group-metadata.js

Update whatsapp version to 2.2208.7. 'Wid' for groupMetaData to avoid "Uncaught Error: GROUP_JID: invalid jid type: Not an instance of WID" in Whatsapp Multi Device
Fixes # .
-
-

'Wid' for GroupMetadata

---

src/lib/wapi/functions/check-send-exist.js

To test out this issue: 
1. Build wapi.js (`npm run build:wapi`).
2. Inject the wapi.js script's content into a browser through developer console.
3. Try execute `window.WAPI.sendMessage('phonenumber@c.us', 'test')` in the console.
Reference Error will be returned instead of sending a message.

Fix sendMessage function throw exception on invalid object

---

src/lib/wapi/functions/check-beta.js
src/lib/wapi/functions/open-chat.js
src/lib/wapi/store/store-objects.js

- Remove `async` from `isBeta`:
- The function does not call `await`, and is called assuming that it does not return a promise.
- Also, the [type definition](https://github.com/orkestral/venom/blob/0a204796998d547da7a3395dcf1985a05edf0935/src/types/WAPI.d.ts#L111) shows it only returning a boolean.
- Remove `default` from the `Cmd` store module:
- The module is defined as a `class` directly under the `Cmd` attribute in recent WhatsApp Web js files
- Module `88102` on [bootstrap_qr.8c19f3b9920c01c16ec8](https://web.whatsapp.com/bootstrap_qr.8c19f3b9920c01c16ec8.js)
To test (it takes a while): `npm install github:matheusb-comp/venom#fix-wapi`

Update WAPI Store Cmd

---

src/lib/wapi/functions/send-link-preview.js

The function sendLinkPreview was sending the Text message as the Title of the preview, it should be the Body of the message

Fix: sendLinkPreview

---

src/lib/wapi/functions/send-file.js

To reproduce the issue, use sendImage or sendFile function to send a file to a WhatsApp contact, the exception will be thrown on accessing the model from mediaCollection.

fix(wapi): sendFile function throw "Cannot read properties of undefined (reading '0')" exception. Issue #1718.

---

src/api/layers/sender.layer.ts

The `buttons` paramater in `sendButtons` has the type of `[]` which prevents anyone using typescript with this library from adding buttons to their message, this pull request fixes that.
- Changes `[]` type on the `sendButtons()` function in `sender.layer.ts` to:
```ts
{
"buttonText": {
"displayText": string
}
}[]
```
To test (it takes a while): `npm install github:nicejs-is-cool/venom#fix-ts-defs`

Fix TypeScript definitions for sendButtons

---

src/lib/wapi/functions/load-all-earlier-chat-messages.js
src/lib/wapi/functions/load-and-get-all-messages-in-chat.js

Acredito ter havido confusão ao trocar a função loadAllEarlierMessages no arquivo loadAndGetAllMessagesInChat. Corrigido loadAllEarlierMessages em seu arquivo e retornado a loadAndGetAllMessagesInChat.

fix: loadAllEarlierMessages e retorno da loadAndGetAllMessagesInChat

---

src/controllers/initializer.ts

Fixes #1889.
Alterado a ordem de iniciar a classe Whatsapp para o load vir antes de navegar na pagina do WPP

fix: alterado ordem de inicialização

---

src/controllers/initializer.ts

The "session" variable has context only inside the create() function, the use of "this.session" returns "undefined" after the project build.
[pt-br] 
A variável "session" possui contexto somente dentro da function create(), o uso do "this.session" retorna "undefined" após o build do projeto.

Context fix for session variable

---

src/lib/wapi/functions/check-send-exist.js

Fixes # .
messages sent to `status@broadcast` are being broadcasted as status, hence it should be allowed to send to the above address.

allow sending to `status@broadcast`

---

src/controllers/initializer.ts

Currently, when a session name is passed to the create function, it ignores any options passed to the options parameter.  This patch fixes that.  Part of fixing #2457

Respect CreateConfig options when using a session name

---

src/lib/wapi/functions/process-message-object.js

Fixes error when processing msg obj:
- Fix a simple bug that occurs when `messageObj` is not a object

Fix Cannot read properties of undefined (reading 'fromMe')

---

src/controllers/browser.ts

Fixes #2457 by allowing headless to be false in addition to 'new' or true.

Allow headless mode to be false

---

src/api/layers/sender.layer.ts
src/lib/wapi/functions/send-link-preview.js
src/types/WAPI.d.ts

`sendLinkPreview` option to send a body message along with the URL and its preview title.
For reference: in the above image, the body message would be:
https://github.com/
Hello

feat: message body option to sendLinkPreview

---

LICENSE

Fixes # .
-  I have changed the copyright year in the license to the "Start year of company"
-  I have changed the copyright owner to the owner name "mentioned in the company website"
To test (it takes a while): `npm install github:gyanavardhana/venom#master`

#2582  updated the copyright year and copyright owner in the license

---

src/config/create-config.ts
src/config/options.ts
src/controllers/browser.ts

Fixes #2631
Fixes #2622
Add a configuration parameter to force webpack version of WhatsApp by dropping the wa_build cookie.
To test (it takes a while): `npm install github:9cb14c2ec0/venom#force_webpack`

Force webpack

---

package.json

Fixes #2571 .
- Since venom is not an ESM module, it can't import dependencies that have converted to ESM format.  So we pin the versions of chrome-launcher and is-root to non-ESM versions
To test (it takes a while): `npm install github:9cb14c1ec0/venom#non-esm`

Fix ERR_REQUIRE_ESM

---

README.md
src/config/create-config.ts
src/config/options.ts
src/controllers/browser.ts
test/index.js

Every time WhatsApp pushes an update to their web app, it is a scramble for project like venom to adapt.  Fortunately, the [wa-version](https://github.com/wppconnect-team/wa-version) repository keeps copies of stable versions of WhatsApp.  We can inject these versions into the browser, and maintain a sense of stability while adapting to changes.
To test (it takes a while): `npm install github:9cb14c1ec0/venom#versioning`

Add versioning capability

---

src/api/whatsapp.ts
src/controllers/browser.ts
src/lib/wapi/api.js
src/lib/wapi/functions/add-chat-wapi.js
src/lib/wapi/functions/help/add-chat-wapi.js
src/lib/wapi/help/inject-paresite.js
src/lib/wapi/store/get-store.js
src/lib/wapi/wapi.js
test/index.js

Now that WhatsApp has moved off of Webpack, this affects how module loading works in venom.  This draft pull request has an initial implementation to support both Webpack and Comet, depending on the version of WhatsApp a user has.  Not all store objects load with this initial attempt, and if anyone knows how to fix that I would be glad to know.
To test (it takes a while): `npm install github:9cb14c1ec0/venom#new_modules`

initial attempt to update module loading

---

README.md

Fixes #2635
The error encountered when calling getNumberProfile is one triggered by WhatsApp javascript calling a function that does not exist.  Since there is no practical way to patch WhatsApp's javascript, the issue should be closed and the documentation updated to note the problem

Update README to indicate getNumberProfile does not work

---

README.md
package-lock.json
package.json
src/api/layers/sender.layer.ts
src/types/WAPI.d.ts
yarn.lock

This function works by injecting keystrokes into the browser page, instead of using javascript hooks.  This maintains the typing indicator properly.
Fixes #2564 
To test (it takes a while): `npm install github:9cb14c1ec0/venom#textviatyping`

Add sendTextViaTyping function

---

src/api/whatsapp.ts

Fixes # .
Backwards compatibility
If no options are set then we should check to see what version of WA is actually running.
If it is less than 2.3 enforce the use of Webpack
Greater than or equal to 2.3 will use new "comet" version
If either options.forceWebpack or options.webVersion are set this will not be processed
-
To test (it takes a while): `npm install github:ghayman/venom#improved-backwards-compatability`

Enforce webpack on versions less than 2.3 when no options are set

---

README.md
src/api/layers/AutomateLayer.ts
src/api/layers/sender.layer.ts

- add sendPhotoVideoViaTyping function, that works by injecting keystrokes.  As with the sendTextViaTyping function, this adds a layer of resiliency by giving multiple independent paths to accomplish tasks.
To test (it takes a while): `npm install github:9cb14c1ec0/venom#typingupdates`

add sendPhotoVideoViaTyping function

---

src/lib/wapi/functions/is-logged-in.js

Fixes:
Issue  #2724
Fixes isLoggedIn() always returning false
To test (it takes a while): `npm install github:<ghayman>/venom#master`

Fixed isLoggedIn() - #2724

---

src/lib/middleware/middleware.ts

Fixes #2713
waitNewAcknowledgements does not seem to be fully implemented. 
The move from addScriptTag to page.evaluate in whatsapp.ts highlighted this issue
Removed the call to the function in middleware.ts
To test (it takes a while): `npm install github:ghayman/venom#window.WAPI.waitNewAcknowledgements-is-not-a-function`

Removed WAPI.waitNewAcknowledgements from middleware

---

src/api/layers/sender.layer.ts
src/types/WAPI.d.ts

Fixes # 2737
Fixes the order in which arguments are passed to WAPI.sendButtons
To test (it takes a while): `npm install github:ghayman/venom#sendButtons-not-working`

Corrected the order of the parameters sent to WAPI.sendButtons

---

src/api/helpers/exposed.enum.ts
src/api/layers/listener.layer.ts
src/api/model/index.ts
src/api/model/reaction.ts
src/lib/wapi/store/store-objects.js
src/types/WAPI.d.ts

Fixes #2797
- Added onMessageReaction() Listener
-
To test (it takes a while): `npm install github:ghayman/venom#reaction-callback`

Added onMessageReaction() listener and callback
